### ISSUE TITLE
Cancelled Missions still stay assigned to slot

### ISSUE THREAD

**Issue by Grizlog** [WonderingPonY/GVSAR#82]
It appears in the Test Server log that while Lebanon missions are being cancelled, units are being removed, Lebanon missions are still staying assigned to user. Switching slots or leaving the server does not fix the issue.

![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/aaab9b8b-e3bd-41b2-b75d-fe3a84eafa16)

**Comment by Grizlog** [comment]
Switching to Haifa slots seem to clear mission assignments, but mission markers aren't being added to the F10 map for any mission now.

**Comment by WonderingPonY** [comment]
This could be a local issue. Sometimes marks don't show for one user but do for another.

**Comment by Grizlog** [comment]
Don't believe it is a local issue, after a restart I was getting marks on every mission in Israel but when i switched to Lebanon, did multiple missions, marks stop populating. Even when switching back to Israel spawn.

**Comment by WonderingPonY** [comment]
This should have been fixed already, server was running incorrect version of the mission. 
Test then close issue please.

**Comment by Grizlog** [comment]
bug still has not been fixed. Missions are staying assigned to slot.

![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/dc6ee36b-74f4-4c2c-8bb7-576cdbf2c934)

**Comment by WonderingPonY** [comment]
Fixed now, it was not removing them from the list because of an error in the table
